### ISSUE TITLE
Change schema for one key based on value of another key

### ISSUE THREAD

**Issue by DaveKLloyd** [keleshev/schema#321]
I would like to make some keys Optional based on the value of another key. For example:

```
some_things:
      access: true
          option1: "option"
          option2: "other option"
```
       
 If access = true option1 and option2 need to be there, if access is false those keys are optional. Actually they are useless, so not necessary.
I guess it doesn't have to be optional perhaps I could use ignore_extra_keys if access is false. 

Can this be done. I have tried a bunch of things and no luck yet.
